# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Maven and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Pull source
      uses: actions/checkout@v1
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: city.newnan.NewNanKits # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    
    - name: Restore Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: restore
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Save Maven cache
      uses: skjolber/maven-cache-github-action@v1
      with:
        step: save
      
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: target/NewNanKits.jar application/octet-stream
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
