# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run Maven and publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Upload to Release
      uses: JasonEtco/upload-to-release@v0.1.1
      with:
        args: my-image.tar application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
